try{
    console.log(NAME);
    const NAME = 'Bruno Mundim';
  } catch(err){
    console.log('Erro:', err)
  }
  
  console.log('Erro tratado corretamente!')